// Generates src/AppIcon.h: the app icon (its dark variant, with rounded corners, on black) as
// RGB888 bitmaps for the Neo's info bar and the +'s touch strip, where the firmware draws it
// beside "ESPDeck". Rerun after changing the icon (ESPDeck Bridge/tools/make_app_icon.swift).
//
//   swift tools/make_screen_icon.swift > src/AppIcon.h

import AppKit

let source = URL( fileURLWithPath: CommandLine.arguments.first! ).deletingLastPathComponent()
	.appendingPathComponent( "../../ESPDeck Bridge/ESPDeck Bridge/Assets.xcassets/AppIcon.appiconset/AppIcon-Dark.png" ).standardized

/// Name and side in pixels: a little shorter than each screen.
let sizes = [ ( "Small", 46 ), ( "Large", 80 ) ]

guard let image = NSImage( contentsOf: source ), let icon = image.cgImage( forProposedRect: nil, context: nil, hints: nil ) else {
	FileHandle.standardError.write( Data( "make_screen_icon: can't read \(source.path)\n".utf8 ) )
	exit( 1 )
}

print( "// Generated by tools/make_screen_icon.swift from the app icon; don't edit." )
print( "// Regenerate with: swift tools/make_screen_icon.swift > src/AppIcon.h" )
print( "" )
print( "#pragma once" )
print( "" )
print( "#include <cstdint>" )
print( "" )
print( "// Square RGB888 bitmaps, top row first, on black." )

for ( name, side ) in sizes {
	let context = CGContext( data: nil, width: side, height: side, bitsPerComponent: 8, bytesPerRow: side * 4,
							 space: CGColorSpace( name: CGColorSpace.sRGB )!, bitmapInfo: CGImageAlphaInfo.noneSkipLast.rawValue )!
	context.setFillColor( CGColor( srgbRed: 0, green: 0, blue: 0, alpha: 1 ) )
	context.fill( CGRect( x: 0, y: 0, width: side, height: side ) )
	// Rounded like an app icon (about 22% of the side), so it reads as one against the black.
	let rect   = CGRect( x: 0, y: 0, width: side, height: side )
	let radius = CGFloat( side ) * 0.225
	context.addPath( CGPath( roundedRect: rect, cornerWidth: radius, cornerHeight: radius, transform: nil ) )
	context.clip()
	context.interpolationQuality = .high
	context.draw( icon, in: rect )

	let pixels = context.data!.assumingMemoryBound( to: UInt8.self )
	var bytes: [String] = []
	for y in 0..<side {
		for x in 0..<side {
			let p = pixels + ( y * side + x ) * 4
			bytes += [ p[0], p[1], p[2] ].map { String( format: "0x%02x", $0 ) }
		}
	}
	print( "" )
	print( "constexpr int kAppIcon\(name)Size = \(side);" )
	print( "constexpr uint8_t kAppIcon\(name)[] = {" )
	for start in stride( from: 0, to: bytes.count, by: 16 ) {
		print( "\t" + bytes[start..<min( start + 16, bytes.count )].joined( separator: ", " ) + "," )
	}
	print( "};" )
}
